### ISSUE TITLE
Doesn't build on current Rust (1.26)

### ISSUE THREAD

**Issue by remram44** [jimmycuadra/ghlabel#6]
```
   Compiling rustc-serialize v0.3.19
error[E0642]: patterns aren't allowed in methods without bodies
   --> /home/remram/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.3.19/src/serialize.rs:147:45
    |
147 |                                             &f_name: &str,
    |                                             ^^^^^^^
```
